In [5]:
import numpy as np
import matplotlib.pyplot as plt
import pandas

In [14]:
# question 1
arr = np.array([0,1,2,3,4,5,6,7,8])

In [15]:
arr.shape

(9,)

In [16]:
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
# question 2
arr2 = np.array(
    [
        0,1,2,3,4,5,6,7,8
    ]
)

In [18]:
for idx, element in enumerate(arr2):
    if element % 2 == 1:
        arr2[idx] = -1
        

In [19]:
arr2

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8])

In [29]:
# question 3
x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89])
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])

In [30]:
x_out_greater = np.array([])
x_out_equal   = np.array([])

In [31]:
for idx, n in enumerate(x):
    if n == y[idx]:
        x_out_equal = np.append(
            x_out_equal, idx
        )
    elif n > y[idx]:
        x_out_greater = np.append(
            x_out_greater,idx
        ) 
    else:
        continue

In [33]:
x_out_greater

array([1., 2., 4., 5., 6., 7., 8., 9.])

In [34]:
x_out_equal

array([0.])

In [35]:
# question 4
assign_4 = np.arange(100).reshape(5,-1)

In [36]:
assign_4

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [37]:
assign_4_modded = assign_4[:,:4]

In [38]:
assign_4_modded

array([[ 0,  1,  2,  3],
       [20, 21, 22, 23],
       [40, 41, 42, 43],
       [60, 61, 62, 63],
       [80, 81, 82, 83]])

In [39]:
# additional exercises

In [40]:
# 1
rng = np.random.default_rng()
arr = rng.integers(30, 41, size = 10)
arr

array([35, 37, 30, 37, 38, 34, 37, 32, 36, 32])

In [54]:
# 2

a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
a3 = np.array([7,8,10])

A = np.array([a1, a2, a3])
B = np.array([a3, a1, a2])

In [55]:
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 10]])

In [56]:
B

array([[ 7,  8, 10],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [57]:
C = A + B

In [58]:
E = A - B

In [59]:
C

array([[ 8, 10, 13],
       [ 5,  7,  9],
       [11, 13, 16]])

In [60]:
E

array([[-6, -6, -7],
       [ 3,  3,  3],
       [ 3,  3,  4]])

In [62]:
A.sum()

46

In [67]:
sumB = np.array([])
for p in range (0, 3):
    sumB = np.append(sumB, B[:, p:p+1].sum())

In [68]:
sumB

array([12., 15., 19.])

In [69]:
sumC = np.array([])
for p in range(0,3):
    sumC = np.append(sumC, C[p:p+1,:].sum())

In [70]:
sumC

array([31., 21., 40.])

In [71]:
D = A @ B

In [72]:
D

array([[ 21,  27,  34],
       [ 57,  72,  91],
       [ 97, 122, 154]])